---
calico:
  - https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
  - https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
Canal:
  - https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/rbac.yaml
  - https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/canal/canal.yaml
# For flannel to work correctly, --pod-network-cidr=10.244.0.0/16 has to be passed to kubeadm init
flannel:
  - kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
Romana:
  - https://raw.githubusercontent.com/romana/romana/master/containerize/specs/romana-kubeadm.yml
