- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: masters
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }

- hosts: nodes
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
