---


- name: Create CNI plugin folder
  file:
    path: /opt/cni-plugin
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0775


- name: Download CNI related resources.
  get_url:
    url: "{{ item }}"
    dest: /opt/cni-plugin
    mode: 755
  with_items: "{{vars[cni]}}"

- name: Apply CNI
  raw: kubectl apply -f /opt/cni-plugin

- name: Remove CNI plugin folder
  file:
    path: /opt/cni-plugin
    state: absent
